name: wild-cloud

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:29
    volumes:
      - ${NEXTCLOUD_VOLUME}:/var/www/html
    depends_on:
      - database
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.localhost`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"

  database:
    container_name: postgres
    image: postgres:17.5
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/initdb.d:/docker-entrypoint-initdb.d
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      POSTHRES_PORT: ${POSTGRES_PORT}
      POSTGRES_JOPLIN_DB: joplin
      POSTGRES_NEXTCLOUD_DB: joplin

  whoami:
    image: traefik/whoami
    container_name: simple-service
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  joplin:
    image: joplin/server:latest
    container_name: joplin
    depends_on:
      - traefik
    environment:
      APP_PORT: 80
      APP_BASE_URL: http://joplin.localhost
      DB_CLIENT: pg
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_JOPLIN_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joplin.rule=Host(`joplin.localhost`)"
      - "traefik.http.routers.joplin.entrypoints=web"

  traefik:
    image: traefik:3.4
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
